# Generated by Django 4.1 on 2024-01-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=20)),
                ("author", models.CharField(max_length=20)),
                ("publisher", models.CharField(max_length=20)),
                ("isbn", models.CharField(max_length=25, unique=True)),
                ("date", models.CharField(max_length=20)),
                ("number", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="book_info",
            fields=[
                (
                    "book_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("position", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                (
                    "isbn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.book",
                        to_field="isbn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="librarian",
            fields=[
                (
                    "id",
                    models.AutoField(
                        default=1000, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="reader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        default=2000, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="reserve",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("reserve_time", models.DateTimeField(default="2000-01-01 00:00:00")),
                (
                    "isbn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.book",
                        to_field="isbn",
                    ),
                ),
                (
                    "reader_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.reader"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="borrow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("borrow_time", models.DateTimeField(default="2000-01-01 00:00:00")),
                ("due_time", models.DateTimeField(default="2000-01-01 00:00:00")),
                ("return_time", models.DateTimeField(default="2000-01-01 00:00:00")),
                ("is_check", models.BooleanField(default=False)),
                ("is_return", models.BooleanField(default=False)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.book_info"
                    ),
                ),
                (
                    "reader_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.reader"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book_info",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.librarian"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.librarian"
            ),
        ),
    ]
